# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d221998926fffd065906d398b35da9d944a1496dd4d5f72a75ac9f50ffd638ece72f322314000300b4f47096ccc2161b7795faf0a6ae6c225b1219c1626cb9d7

test:
  secret_key_base: e4ddd3a0a307899a8fd81cc341b8710989683b01363a4c14d8eabda382c8568a65e98746275af7c70f94c5e389cf9bedaa076c8541f676f6fef0211ca147ebc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
